python check_updated.py --file_mode default 
python check_updated.py --file_mode p 
python check_updated.py --file_mode r 
python check_updated.py --file_mode a 
python check_updated.py --file_mode f 
python check_updated.py --file_mode pr 
python check_updated.py --file_mode pa 
python check_updated.py --file_mode pf 
python check_updated.py --file_mode ra 
python check_updated.py --file_mode rf 
python check_updated.py --file_mode af 
python check_updated.py --file_mode pra
python check_updated.py --file_mode prf 
python check_updated.py --file_mode paf 
python check_updated.py --file_mode raf 
python check_updated.py --file_mode praf 