CUDA_VISIBLE_DEVICES=0 nohup torchrun --master_port 7710 run_agent_api_default.py --test_model_name Mistral-8X7B-instruct-v0.1 --mode planning --category algebra --start_index 0 --original_correct 0 --ip http://10.166.180.57:8080 > ./log/new_algebra/Mistral-8X7B-instruct-v0.1/multi/p_new.out 2>&1 &
CUDA_VISIBLE_DEVICES=0 nohup torchrun --master_port 7711 run_agent_api_default.py --test_model_name Mistral-8X7B-instruct-v0.1 --mode reasoning --category algebra --start_index 0 --original_correct 0 --ip http://10.166.180.57:8080 > ./log/new_algebra/Mistral-8X7B-instruct-v0.1/multi/r_new.out 2>&1 &
CUDA_VISIBLE_DEVICES=0 nohup torchrun --master_port 7712 run_agent_api_default.py --test_model_name Mistral-8X7B-instruct-v0.1 --mode action --category algebra --start_index 0 --original_correct 0 --ip http://10.166.180.57:8080 > ./log/new_algebra/Mistral-8X7B-instruct-v0.1/multi/a_new.out 2>&1 &
CUDA_VISIBLE_DEVICES=0 nohup torchrun --master_port 7713 run_agent_api_default.py --test_model_name Mistral-8X7B-instruct-v0.1 --mode reflection --category algebra --start_index 0 --original_correct 0 --ip http://10.166.180.57:8080 > ./log/new_algebra/Mistral-8X7B-instruct-v0.1/multi/f_new.out 2>&1 & 
CUDA_VISIBLE_DEVICES=0 nohup torchrun --master_port 7714 run_agent_api_default.py --test_model_name Mistral-8X7B-instruct-v0.1 --mode planning action  --category algebra --start_index 0 --original_correct 0 --ip http://10.166.180.57:8080 > ./log/new_algebra/Mistral-8X7B-instruct-v0.1/multi/pa_new.out 2>&1 &


CUDA_VISIBLE_DEVICES=0 nohup torchrun --master_port 7715 run_agent_api_default.py --test_model_name Mistral-8X7B-instruct-v0.1 --mode planning reasoning --category algebra --start_index 0 --original_correct 0 --ip http://10.166.180.57:8080 > ./log/new_algebra/Mistral-8X7B-instruct-v0.1/multi/pr_new.out 2>&1 &
CUDA_VISIBLE_DEVICES=0 nohup torchrun --master_port 7716 run_agent_api_default.py --test_model_name Mistral-8X7B-instruct-v0.1 --mode planning reflection --category algebra --start_index 0 --original_correct 0 --ip http://10.166.180.57:8080 > ./log/new_algebra/Mistral-8X7B-instruct-v0.1/multi/pf_new.out 2>&1 &
CUDA_VISIBLE_DEVICES=0 nohup torchrun --master_port 7717 run_agent_api_default.py --test_model_name Mistral-8X7B-instruct-v0.1 --mode reasoning reflection --category algebra --start_index 0 --original_correct 0 --ip http://10.166.180.57:8080 > ./log/new_algebra/Mistral-8X7B-instruct-v0.1/multi/rf_new.out 2>&1 &
CUDA_VISIBLE_DEVICES=0 nohup torchrun --master_port 7718 run_agent_api_default.py --test_model_name Mistral-8X7B-instruct-v0.1 --mode action reflection --category algebra --start_index 0 --original_correct 0 --ip http://10.166.180.57:8080 > ./log/new_algebra/Mistral-8X7B-instruct-v0.1/multi/af_new.out 2>&1 &
CUDA_VISIBLE_DEVICES=0 nohup torchrun --master_port 7719 run_agent_api_default.py --test_model_name Mistral-8X7B-instruct-v0.1 --mode reasoning action --category algebra --start_index 0 --original_correct 0 --ip http://10.166.180.57:8080 > ./log/new_algebra/Mistral-8X7B-instruct-v0.1/multi/ra_new.out 2>&1 &


CUDA_VISIBLE_DEVICES=0 nohup torchrun --master_port 7720 run_agent_api_default.py --test_model_name Mistral-8X7B-instruct-v0.1 --mode planning reasoning action --category algebra --start_index 0 --original_correct 0 --ip http://10.166.186.2:8080 > ./log/new_algebra/Mistral-8X7B-instruct-v0.1/multi/pra_new.out 2>&1 &
CUDA_VISIBLE_DEVICES=0 nohup torchrun --master_port 7721 run_agent_api_default.py --test_model_name Mistral-8X7B-instruct-v0.1 --mode planning action reflection --category algebra --start_index 0 --original_correct 0 --ip http://10.166.186.2:8080 > ./log/new_algebra/Mistral-8X7B-instruct-v0.1/multi/paf_new.out 2>&1 &
CUDA_VISIBLE_DEVICES=0 nohup torchrun --master_port 7722 run_agent_api_default.py --test_model_name Mistral-8X7B-instruct-v0.1 --mode planning reasoning reflection --category algebra --start_index 0 --original_correct 0 --ip http://10.166.186.2:8080 > ./log/new_algebra/Mistral-8X7B-instruct-v0.1/multi/prf_new.out 2>&1 & 
CUDA_VISIBLE_DEVICES=0 nohup torchrun --master_port 7723 run_agent_api_default.py --test_model_name Mistral-8X7B-instruct-v0.1 --mode reasoning action reflection --category algebra --start_index 0 --original_correct 0 --ip http://10.166.186.2:8080 > ./log/new_algebra/Mistral-8X7B-instruct-v0.1/multi/raf_new.out 2>&1 &
CUDA_VISIBLE_DEVICES=0 nohup torchrun --master_port 7724 run_agent_api_default.py --test_model_name Mistral-8X7B-instruct-v0.1 --mode planning reasoning action reflection --category algebra --start_index 0 --original_correct 0 --ip http://10.166.186.2:8080 > ./log/new_algebra/Mistral-8X7B-instruct-v0.1/multi/praf_new.out 2>&1 &
